# alacritty.toml
# https://alacritty.org/config-alacritty.html

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[window]
#opacity = 0.9
#blur= true

padding.x = 5
padding.y = 5

#decorations = "Full"
#decorations_theme_variant = "Dark"

[font]
size = 17

normal  = {family = "SF Mono", style = "Regular" }
bold    = {family = "SF Mono", style = "Bold" }
italic  = {family = "SF Mono", style = "Italic" }
bold_italic    = {family = "SF Mono", style = "Bold Italic" }

[terminal]
#shell = "$SHELL"

